server:
  port: 9000
spring:
  velocity:
    charset: UTF-8
    properties.input.encoding: UTF-8
    properties.output.encoding: UTF-8
    resourceLoaderPath: classpath:/templates/
    prefix: /
    # toolbox-config-location: /WEB-INF/toolbox.xml
  datasource:
    name: commerce
    url: jdbc:mysql://127.0.0.1:3306/commerce?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 111111
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 20
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.entity